### PR TITLE
chore(package): update mocha to version 4.0.1

### PR DESCRIPTION
**Pull request by bergie**
Closes #207

### CODE REVIEW

**Comment by bergie** [comment]
Kind of curious how the build hangs after all tests pass. Seeing same behavior with noflo/noflo-runtime-websocket#77

@jonnor ideas?

**Comment by jonnor** [comment]
@bergie Mocha 4 will no longer forcefully stop the tests when done. So any nodejs thing still active will keep it hanging. Mentioned in its changelog

**Comment by bergie** [comment]
@jonnor ok, so the issue is that we have some MQTT/AMQP connections left hanging or somesuch?

**Comment by jonnor** [comment]
Yes or any other deferred thing, like a setInterval. msgflo-nodejs is happy with Mocha 4 though. Probably need to check with one of the Nodejs debugging tools for this kind of problem

**Comment by bergie** [comment]
Here is a way to see what's hanging: https://stackoverflow.com/a/32617487/263570

**Pull request merged**
